import Head from 'next/head'
import styles from '../styles/Home.module.css'
import getStats from '../components/nfts/services/get_stats';


function Home({ nfts }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Truth Labs raffle ticket calculator
        </h1>

        <h2>Best Price to get a Raffle Ticket</h2>

        <table>
          <thead>
            <tr>
              <th>NFT</th>
              <th>Points</th>
              <th>Floor</th>
              <th>#/Raffle</th>
              <th>Cost/Raffle</th>
            </tr>
          </thead>
          <tbody>
            {nfts.map(({ name, slug, points, floor_price, perRaffle, stats, costPerRaffle }) => (
              <tr key={slug}>
                <td>{name}</td>
                <td>{points}</td>
                <td>{floor_price.toFixed(5)}</td>
                <td>{perRaffle.toFixed(2)}</td>
                <td>{costPerRaffle.toFixed(5)}</td>
              </tr>
            ))}

          </tbody>
        </table>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export async function getStaticProps() {
  const allIncludedObject = await getStats();
  const allIncludedEnrichedArray = Object.values(allIncludedObject);
  const statObject = allIncludedEnrichedArray.reduce((current, included) => ([...current, { ...included, }]), [])

  return {
    props: {
      nfts: statObject
    },
    revalidate: 60, // In seconds
  }
}

export default Home